import{$,parseMD}from'./utils.js';
import{stream}from'./api.js';
import{getMsgs,addMsg}from'./memory.js';
let abort=null,typing=false;
export function init(){renderHist();$('#chatForm')?.addEventListener('submit',e=>{e.preventDefault();const v=$('#chatInput').value.trim();if(!v||typing)return;send(v);$('#chatInput').value=''});document.addEventListener('click',e=>{if(e.target.closest('[data-action="chat"]')){window.dispatchEvent(new CustomEvent('nav',{detail:{tab:'chat'}}));setTimeout(()=>$('#chatInput')?.focus(),300)}})}
function renderHist(){const c=$('#chatContainer'),m=getMsgs();if(!c||!m.length)return;c.querySelector('.chat-welcome')?.remove();m.forEach(x=>bubble(x.role,x.content,false));scroll()}
function bubble(role,content,anim=true){const c=$('#chatContainer');if(!c)return;c.querySelector('.chat-welcome')?.remove();const d=document.createElement('div');d.className=`chat-message ${role}`;d.innerHTML=`<div class="chat-avatar">${role==='user'?'You':'NX'}</div><div class="chat-bubble">${parseMD(content)}</div>`;c.appendChild(d);if(anim)scroll()}
function scroll(){const c=$('#chatContainer');if(c)c.scrollTop=c.scrollHeight}
async function send(text){const ind=$('#typingIndicator');bubble('user',text);addMsg('user',text);typing=true;ind?.classList.add('active');const ai=document.createElement('div');ai.className='chat-message';ai.innerHTML=`<div class="chat-avatar">NX</div><div class="chat-bubble" id="aiBubble"><em>Thinking...</em></div>`;$('#chatContainer')?.appendChild(ai);scroll();const bub=$('#aiBubble');let full='';const cfg=JSON.parse(localStorage.getItem('nx_api')||'{}');if(!cfg.endpoint){full=`**Noctryx AI** is ready, but no backend is configured.\n\nGo to **More > API Config** to set your endpoint.\n\nYou asked: "${text}"`;if(bub)bub.innerHTML=parseMD(full);addMsg('assistant',full);done();return}const hist=getMsgs().slice(-20).map(m=>({role:m.role,content:m.content}));try{abort=await stream(hist,ch=>{full+=ch;if(bub)bub.innerHTML=parseMD(full);scroll()},()=>{addMsg('assistant',full);done()},err=>{full+=`\n\n_Error: ${err.message}_`;if(bub)bub.innerHTML=parseMD(full);addMsg('assistant',full);done()})}catch(e){full+=`\n\n_Error: ${e.message}_`;if(bub)bub.innerHTML=parseMD(full);addMsg('assistant',full);done()}}
function done(){typing=false;$('#typingIndicator')?.classList.remove('active');const b=$('#aiBubble');if(b)b.removeAttribute('id')}
export function stop(){if(abort){abort.abort();abort=null}}
