import{$,formatBytes}from'./utils.js';
const S={battery:null,connection:null,storage:null};
export async function init(){updTime();setInterval(updTime,1000);updBasic();initBat();initNet();initStore();initMem();updCore();setInterval(initStore,30000);setInterval(updCore,5000)}
function updTime(){const n=new Date();window.__nx_time=n.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});window.__nx_date=n.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}
function updBasic(){const i={browser:navigator.userAgent.includes('Firefox')?'Firefox':navigator.userAgent.includes('Chrome')?'Chrome':navigator.userAgent.includes('Safari')?'Safari':'Unknown',platform:navigator.platform||'Unavailable',online:navigator.onLine?'Online':'Offline',resolution:`${screen.width}x${screen.height}`,language:navigator.language||'Unavailable',cores:navigator.hardwareConcurrency||'Unavailable'};window.__nx_sys=i;const d=$('#aiStatusDot'),t=$('#aiStatusText');if(!navigator.onLine){d?.classList.add('offline');if(t)t.textContent='AI CORE: OFFLINE'}else{d?.classList.remove('offline');if(t)t.textContent='AI CORE: ACTIVE'}window.addEventListener('online',()=>{d?.classList.remove('offline');if(t)t.textContent='AI CORE: ACTIVE'});window.addEventListener('offline',()=>{d?.classList.add('offline');if(t)t.textContent='AI CORE: OFFLINE'})}
async function initBat(){const el=$('#batteryVal'),fi=$('#batteryFill');if('getBattery'in navigator){try{const b=await navigator.getBattery();S.battery=b;const up=()=>{const p=Math.round(b.level*100);const c=b.charging;if(el)el.textContent=`${p}%${c?' \u26a1':''}`;if(fi)fi.style.width=`${p}%`};up();b.addEventListener('levelchange',up);b.addEventListener('chargingchange',up)}catch{if(el)el.textContent='Unavailable'}}else{if(el)el.textContent='Unavailable'}}
function initNet(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;$('#cpuVal').textContent='Unavailable';$('#cpuFill').style.width='0%';if('deviceMemory'in navigator){$('#ramVal').textContent=`~${navigator.deviceMemory} GB`;$('#ramFill').style.width='0%'}else{$('#ramVal').textContent='Unavailable'}if(c){S.connection=c;window.__nx_net={type:c.effectiveType||'unknown',downlink:c.downlink||'unknown'}}}
async function initStore(){const el=$('#storageVal'),fi=$('#storageFill');if('storage'in navigator&&'estimate'in navigator.storage){try{const e=await navigator.storage.estimate();S.storage=e;const u=e.usage||0,q=e.quota||1,p=Math.round((u/q)*100);if(el)el.textContent=`${p}%`;if(fi)fi.style.width=`${p}%`;window.__nx_store={used:formatBytes(u),total:formatBytes(q),pct:p}}catch{if(el)el.textContent='Unavailable'}}else{if(el)el.textContent='Unavailable'}}
function initMem(){if('performance'in window&&'memory'in performance){const m=performance.memory;window.__nx_heap={used:formatBytes(m.usedJSHeapSize),total:formatBytes(m.totalJSHeapSize),limit:formatBytes(m.jsHeapSizeLimit)}}}
function updCore(){const cp=$('#corePct'),cr=$('#coreRing'),cs=$('#coreStatusText');let h=100;if(S.battery)h=Math.min(h,Math.round(S.battery.level*100));if(S.storage){const sp=Math.round(((S.storage.usage||0)/(S.storage.quota||1))*100);h=Math.min(h,100-sp)}if(!navigator.onLine)h=Math.min(h,30);const c=2*Math.PI*38,o=c-(h/100)*c;if(cr)cr.style.strokeDashoffset=o;if(cp)cp.textContent=`${h}%`;let s='RUNNING SMOOTHLY';if(h<50)s='MODERATE LOAD';if(h<25)s='SYSTEM STRAINED';if(!navigator.onLine)s='OFFLINE MODE';if(cs)cs.textContent=s}
export const getInfo=()=>({...window.__nx_sys,time:window.__nx_time,date:window.__nx_date,network:window.__nx_net,storage:window.__nx_store,heap:window.__nx_heap,battery:S.battery?{level:Math.round(S.battery.level*100),charging:S.battery.charging}:null});
