export const $=(s,e=document)=>e.querySelector(s);
export const $$=(s,e=document)=>Array.from(e.querySelectorAll(s));
export const debounce=(fn,ms=300)=>{let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};
export const formatBytes=(b,d=1)=>{if(!b)return'0 B';const k=1024,s=['B','KB','MB','GB','TB'];const i=Math.floor(Math.log(b)/Math.log(k));return parseFloat((b/Math.pow(k,i)).toFixed(d))+' '+s[i]};
export const timeAgo=d=>{const s=Math.floor((Date.now()-new Date(d))/1000);const v=[[31536000,'y'],[2592000,'mo'],[86400,'d'],[3600,'h'],[60,'m'],[1,'s']];for(const[x,l]of v){const c=Math.floor(s/x);if(c>=1)return c+l+' ago'}return'just now'};
export const esc=s=>{const d=document.createElement('div');d.textContent=s;return d.innerHTML};
export const parseMD=t=>{let h=esc(t);h=h.replace(/```(\w+)?\n([\s\S]*?)```/g,(_,l,c)=>`<pre><code class="language-${l||'text'}">${c.trim()}</code></pre>`);h=h.replace(/`([^`]+)`/g,'<code>$1</code>');h=h.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>');h=h.replace(/\*(.*?)\*/g,'<em>$1</em>');h=h.replace(/^- (.*$)/gim,'<li>$1</li>');h=h.replace(/(<li>.*<\/li>\n?)+/g,m=>`<ul>${m}</ul>`);h=h.replace(/\[([^\]]+)\]\(([^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>');return h.split(/\n\s*\n/).map(b=>{b=b.trim();if(!b)return'';if(b.startsWith('<'))return b;return`<p>${b.replace(/\n/g,'<br>')}</p>`}).join('\n')};
export const genId=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
export const save=(k,d)=>{try{localStorage.setItem('nx_'+k,JSON.stringify(d))}catch(e){}};
export const load=(k,f=null)=>{try{const r=localStorage.getItem('nx_'+k);return r?JSON.parse(r):f}catch(e){return f}};
export const speak=(t,r=1,p=1)=>new Promise((res,rej)=>{if(!('speechSynthesis'in window))return rej();const u=new SpeechSynthesisUtterance(t);u.rate=r;u.pitch=p;u.onend=res;u.onerror=rej;window.speechSynthesis.speak(u)});
